- name: RabbitMQ
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  vars_prompt:
    - name: 'rabbitmq_selection'
      prompt: "Choose serial number to install RabbitMQ \n
      1: rabbitmq 3.6\n
      2: rabbitmq 3.7\n
      3: rabbitmq 3.8\n
      4: rabbitmq 3.9\n"
      private: no
      default: 4

  vars:
    rabbitmq_select:
      '1': "3.6"
      '2': "3.7"
      '3': "3.8"
      '4': "3.9"

    rabbitmq_version: "{{rabbitmq_select[rabbitmq_selection]}}"  

  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
    - {role: role_rabbitmq, tags: "role_rabbitmq"}
    - {role: role_init, tags: "role_init"}
    - {role: role_preend, tags: "role_preend"}
    - {role: role_end, tags: "role_end"}